neveinNadeen/Models/Directors.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace neveinNadeen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Directors
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Directors()
        {
            this.FavDirectors = new HashSet<FavDirectors>();
            this.IMDb_User = new HashSet<IMDb_User>();
            this.Movies = new HashSet<Movies>();
        }
    
        public int Id { get; set; }
        public string Fname { get; set; }
        public string Lname { get; set; }
        public Nullable<int> Age { get; set; }
        public string Image { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FavDirectors> FavDirectors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IMDb_User> IMDb_User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Movies> Movies { get; set; }
    }
}

neveinNadeen/Controllers/DirectorController.cs
using neveinNadeen.Models;
using neveinNadeen.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace neveinNadeen.Controllers
{
    public class DirectorController : Controller
    {
        // GET: Director
        public IMDb_Entities db = new IMDb_Entities();

        public ActionResult Index(string searching)
        {

            return View(db.Directors.Where(x => x.Fname.Contains(searching)).ToList());

        }
        //public ActionResult Details(int id)
        //{
        //    var directors = db.Directors.SingleOrDefault(a => a.Id == id);
        //    return View(directors);
        //}

        public ActionResult Details(int id)
        {
            ActorMovieDirector a = new ActorMovieDirector
            {
                Director = db.Directors.SqlQuery("select * from director where id = " + id).ToList(),
                Movie = db.Movies.SqlQuery($"select * from movie WHERE movie.D_id={id} ").ToList(),
            };
            return View(a);
        }

    }
}

neveinNadeen/Views/Director/Details.cshtml
@model neveinNadeen.ViewModels.ActorMovieDirector

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href="~/Styles/detailsActorDirector.css" rel="stylesheet" />

</head>


<body>
    @{
        string name = "";

    }
    <div class="container">
        <div class="row">
            <div class="col-1"></div>
            <div class="col-9 ">
                <div class="row content">
                    <div class="col-7">
                        <table class="table table-borderless">
                            <tbody>
                                @foreach (var item in Model.Director)
                                {
                                    <tr><td><div width="100" height="250"> <img class"main-img" src="~/images/directors/@item.Image" style="width: 150px; height:205px ;margin-left:140px" /></div></td></tr>
                                    <tr>
                                        <td>
                                            <h4>Name:</h4>
                                            <span>@Html.DisplayFor(modelItem => item.Fname) @Html.DisplayFor(modelItem => item.Lname)</span>

                                        </td>
                                    </tr>

                                    <tr>
                                        <td>
                                            <h4>Age:</h4>
                                            <span>@Html.DisplayFor(modelItem => item.Age) </span>

                                        </td>
                                    </tr>
                                }
                                <tr><td><h4>Filmography: </h4></td></tr>
                                <tr style="display:flex;flex-direction:row;flex-wrap:wrap;">
                                    @foreach (var item in Model.Movie)
                                    {
                                        name = @Html.DisplayFor(modelItem => item.Name).ToString();

                                        <td>
                                            <div class="card" style="width: 150px; height:215px">
                                                <img src="~/images/movies/@item.Image" style="" />
                                                <div class="card-body text-center">
                                                    <div class="small-box" style="margin-top:-15px;">
                                                        <h6>@Html.ActionLink(name, "Details", "Movie", new { id = item.Id }, new { style = "text-decoration:none;width:min-width; color: black;padding:7px;" })</h6>
                                                    </div>
                                                </div>
                                            </div>
                                        </td>
                                    }

                                </tr>

                              
                            </tbody>
                        </table>
                    </div>

                    <div class="col-4" style="margin-top:40px">
                        <div class="row">
                            <div class="card">
                                <div class="card-body">
                                    <p class="card-title">IMDB News<hr /></p>

                                    <div id="carouselExampleSlidesOnly" class="carousel slide" data-bs-ride="carousel">
                                        <div class="carousel-inner" style="font-size:larger;">
                                            <div class="carousel-item active">
                                                <p>New movies were added</p>
                                            </div>
                                            <div class="carousel-item">
                                                <p>Doctor Strange in the Multiverse of Madness (2022)</p>
                                            </div>
                                            <div class="carousel-item">
                                                <p>The Bad Guys (2022)</p>
                                            </div>

                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <br />
                        <div class="row">
                            <div class="card">
                                <div class="card-body">
                                    <p class="card-title">Share this page</p>
                                    <input type="button" value="Copy Url" onclick="Copy();" />
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
            <div class="col-1"></div>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>
<script>
    function Copy() {
        let url = document.location.href

        navigator.clipboard.writeText(url).then(function () {
            console.log('Copied!');
        }, function () {
            console.log('Copy error')
        });

    }
</script>

neveinNadeen/Views/Director/Index.cshtml
@model IEnumerable<neveinNadeen.Models.Director>


@{
    /**/

    ViewBag.Title = "Directors";
}


<!DOCTYPE html>
<html>
<head>
    <link href="~/Styles/Index.css" rel="stylesheet" />
</head>
<body>
    <form class="form-inline" style="">
        @using (Html.BeginForm("Index", "Director", FormMethod.Get))
        {

            <div style="">
                <input id="searching" name="searching" class="form-control mr-sm-2" type="text" placeholder="Search IMDb" aria-label="Search" style="">
                <input class="btn btn-outline-warning" type="submit" value="Search" style="">

            </div>

        }
    </form>

    @{
        string name = "";

    }


    <table class="table table-striped">

        @foreach (var item in Model)
        {
            name = @Html.DisplayFor(modelItem => item.Fname).ToString() + " " + @Html.DisplayFor(modelItem => item.Lname).ToString();
            <tr>
                <td width="200" height="150">
                    <img src="~/images/directors/@item.Image" width="100" height="150" />
                </td>
                <td style="padding-top:75px ; font-size:20px">

                    <div class="small-box"><span class="name">@Html.ActionLink(name, "Details", "Director", new { id = item.Id }, new { style = "" })</span></div>
                </td>

            </tr>
        }

    </table>
</body>
</html>